[package]
name = "client-api"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.8", features = ["d3d9", "libloaderapi", "winuser", "winver"] }
detour = { git = "https://github.com/darfink/detour-rs", rev = "3b6f17a" }
log = "0.4.14"
