[package]
name = "client-api"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.8", features = ["d3d9", "libloaderapi", "winuser", "winver"] }
retour = "0.3.1"
log = "0.4.14"
